# I want to define the database layer in this file. At some point, I will also
# add the application / Spring Boot layer.
services:
  db:
    image: postgres:17.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend
  flyway:
    image: redgate/flyway:11.10.0
    container_name: flyway
    volumes:
      # we will execute migrations in here
      - ./src/main/resources/db/migration:/flyway/sql
    environment:
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_URL: jdbc:postgresql://db:5432/postgres
      FLYWAY_CLEAN_DISABLED: "false"
    depends_on:
      - db
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    networks:
      - backend

networks:
    backend: